### ISSUE TITLE
heroku - Site Deployment

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorGlassWeb#30]
Grunt Build Script Option to Automate deployment

**Comment by Cristialt** [comment]
I've scketched the deploy approach, using this npm `grunt-heroku-deploy` plugin which is straight forward..

Having dev on master `git branch --set-upstream master origin/master`

We'll set up a deploy branch to push from 
`git checkout -b deploy; git branch --set-upstream deploy heroku/master`

`grunt heroku-deploy` does:
`git checkout deploy`
`git merge master`
`git push`
`git checkout master`

We'll need some credentials so I can test it and complete the job

**Comment by stuartshay** [comment]
Christi

I already got the deployment setup on the admin console 

Since you said you were not sure with grunt deployment I gave this to someone else 

If you want to take a look feel free i am on a very limited budget so I don't   Want to pay for the same work twice

Stuart

**Comment by Cristialt** [comment]
Oh, it's okay, I just wanted to finish this - it's angular I'm not very familiar with. I'll revert.

**Comment by stuartshay** [comment]
If it works you can leave it for now

I am going to have the guy helping me look at it

**Comment by stuartshay** [comment]
Christi:

 

The Work on my end is going to take a few more days.

 

If you can get the site setup using your Heroku Account (Just use the Free Version)  I have no problem paying for your time.

 

Once it is working it is very easy for me to use the same Config for my instance

 

Stuart

**Comment by Cristialt** [comment]
Ah, okay, will do that tomorrow then.
thanks
Cristi

**Comment by stuartshay** [comment]
Christi

Made allot progress with server side and client functionality

The deployment is taking allot of work, the good news I got a guy who is a expert and we are working on the issues. If you are having trouble with Herkou it can wait at one time the site did work

Stuart

**Comment by Cristialt** [comment]
Hi, I don't get it, should I leave it for later on or what?

**Comment by stuartshay** [comment]
Christi

If you can do it then great,  if you are not sure it is not a problem 



Stuart

**Comment by Cristialt** [comment]
FYI, I worked on the issue this afternoon, everything seems fine but I still have a problem with heroku's remote actions, it crashes with no too much explanation but I'll fix that somehow

**Comment by Cristialt** [comment]
update: 
Yeah, indeed everything was fine and Heroku woke up and did it right this time... 
I just need to adjust the Grunt task and this is sorted.

**Comment by stuartshay** [comment]
Christi

Great, it was real hard getting the deployment to work in the other project

By deploying it makes it easier to review on both ends

Stuart

**Comment by Cristialt** [comment]
I am now geting 'cannot get /' and I know I've sorted that locally but can't remember what was it. 
Do you know what's causing it? 
https://navigatorglassweb.herokuapp.com/

**Comment by stuartshay** [comment]
Not sure I had someone else do this

If you have issues with getting this too work I can this to the other guy I have,  he has done this many times 

It could be a package dependency that is not correct

Check the Heroku log it might be helpfull

Stuart

**Comment by Cristialt** [comment]
No I think it's all about the production tasks, checking and fixng those one by one atm.

**Comment by Cristialt** [comment]
these are the remaining ones.. 
![screen shot 2015-01-14 at 21 32 23](https://cloud.githubusercontent.com/assets/5858729/5745946/e67e0dc2-9c34-11e4-833d-c33899f98829.png)

**Comment by stuartshay** [comment]
When you run in Heriku make sure to use http and NOT https

This needs to be setup this was issue

**Comment by Cristialt** [comment]
same with http, and the build task generates functional app, although it says 

`http://navigatorglassweb.cloudapp.net/api/timeline Failed to load resource: the server responded with a status of 400 (Bad Request)` 

but I believe this is something else...

**Comment by Cristialt** [comment]
Let's give it to the other guy maybe he'll be able to fix it in minutes. 
I've seen the dist/ folder was ignored by git, I have added it and deployed again, stil nothing. Besides that the deployment works fine. Let's see what he says

**Comment by stuartshay** [comment]
Ok 

Sounds good

I will get back you when I have it working

Stuart

**Comment by Cristialt** [comment]
Thanks, 
Don't forget npm install && bower install as I have moved the pkgs around

Cristi

**Comment by Cristialt** [comment]
Ran the app locally using foreman, works well, the deploy looks good and still getting 'cannot get /'

**Comment by stuartshay** [comment]
Christi

With the deployment, the API should point to the same Url's as grunt serve:mock

This should not make a difference, i was tired last night so I did chat with the guy helping with this

Stuart

**Comment by stuartshay** [comment]
Christi

I had the guy look at the deployment, he said the issue was Sass with using Ruby it causes too many issues

He converted the Sass to less, most of it the same anyway

I did not test the deployment yet but it should be working

I will keep you up to date, I should have new work soon

Stuart

**Comment by Cristialt** [comment]
Ah sorry yeah  !! I forgot it's Sass with Ruby
It's better with Ruby but needs extra work for deployment indeed. 
And if he turned it to to less the deployment will surely work

**Comment by stuartshay** [comment]
Christi:

 

The Other guy got the deployment to work,  he is working on the CSS and other fixes, but locally the code looks good.

 

In the Past there has  been allot of pain with deployment, so the best way I would like to do things is deploy the code to your Heroku Instance and we can work on changes and new requirements before the code is checked in

 

Here is the working copy

http://desolate-basin-6008.herokuapp.com/#/timeline

 

We can pick up now at a faster pace, now that I got allot of the code deployed to the Cloud

 

Thanks Again

Stuart

**Comment by leduong** [comment]
Hi!

This is example on CRUD by nodejs

```
var db = require('../models'),
	_ = require('lodash');

exports.findAll = function (req, res) {
	var q = req.query.q || "",
		sort = req.query.sort || "id",
		order = req.query.order || "asc",
		page = parseInt(req.query.page) || 1,
		limit = parseInt(req.query.limit) || 20,
		group = req.query.group || "",
		offset = ((page - 1) * limit),
		query = {
			order: sort + ' ' + order,
			offset: offset,
			limit: limit
		};

	if (group) {
		query = _.merge({
			group: group
		}, query);
	};

	if (q) {
		query = _.merge({
			// where: ["name LIKE '%" + q + "%'"] // uncomment for use
		}, query);
	};

	db.User.findAndCountAll(query)
		.then(function (result) {
			res.jsonp({
				total: result.count,
				page: page,
				limit: limit,
				from: offset + 1,
				to: offset + result.rows.length,
				results: result.rows
			});
		})
}

exports.find = function (req, res) {
	db.User.find({
		where: {
			id: req.param('id')
		}
	}).success(function (entity) {
		if (entity) {
			res.json(entity)
		} else {
			res.sendStatus(404)
		}
	})
}

exports.create = function (req, res) {
	db.User.create(req.body).success(function (entity) {
		res.statusCode = 201
		res.json(entity)
	}).error(function (error) {
		res.set('X-Status-Reason', error);
		res.sendStatus(400)
	});
}

exports.update = function (req, res) {
	db.User.find({
		where: {
			id: req.param('id')
		}
	}).success(function (entity) {
		if (entity) {
			entity.updateAttributes(req.body).success(function (entity) {
				res.json(entity)
			}).error(function (error) {
				res.set('X-Status-Reason', error);
				res.sendStatus(400)
			});
		} else {
			res.sendStatus(404)
		}
	})
}

exports.destroy = function (req, res) {
	db.User.find({
		where: {
			id: req.param('id')
		}
	}).success(function (entity) {
		if (entity) {
			entity.destroy().success(function () {
				res.sendStatus(204)
			}).error(function (error) {
				res.set('X-Status-Reason', error);
				res.sendStatus(400)
			});
		} else {
			res.sendStatus(404)
		}
	})
}
```

You look 'res.set('X-Status-Reason', error);' it's return error.

on AngluarJS

```
		$provide.factory('ddInterceptor', [
			'$q', '$rootScope', '$injector', '$location', 'AuthToken', 'REQUIRE_AUTH',
			function ($q, $rootScope, $injector, $location, AuthToken, REQUIRE_AUTH) {
				var currentPath, exports, payloadData, ref;
				currentPath = void 0;
				payloadData = void 0;
				ref = void 0;
				exports = {
					request: function (config) {
						var auth;
						auth = AuthToken.get();
						if (auth) {
							config.headers = config.headers || {};
							config.headers.Authorization = 'Bearer ' + auth.token;
						}
						return config;
					},
					response: function (response) {
						var errors;
						if (response.headers()['content-type'] === 'application/json' || response.headers()['content-type'] === 'application/json; charset=utf-8') {
							if (response.data.code >= 400) {
								errors = response.data.errors || [];
								if (errors) {
									angular.forEach(errors, function (error) {
										$rootScope.$broadcast('error', error.path + ': ' + error.message);
									});
								}
								if (response.data.code === 400) {
									if (!errors) {
										$rootScope.$broadcast('error', response.data.message || 'Error. 400 Bad Request.');
									}
								}
								if (response.data.code === 401) {
									if (!errors) {
										$rootScope.$broadcast('error', response.data.message || 'Error. 401 Unauthorized.');
									}
									currentPath = $location.path();
									if (currentPath !== REQUIRE_AUTH || currentPath !== '/user/signout' || currentPath !== '/user/signup') {
										ref = $location.$$url;
										$location.path('/user/signout').search({
											ref: ref
										});
									}
								}
								if (response.data.code === 403) {
									if ($location.path() !== REQUIRE_AUTH) {
										if (!errors) {
											$rootScope.$broadcast('error', response.data.message || 'Error. 403 Forbidden.');
										}
										$location.path(REQUIRE_AUTH);
									}
								}
								if (response.data.code === 404) {
									if ($location.path() !== REQUIRE_AUTH) {
										if (!errors) {
											$rootScope.$broadcast('error', response.data.message || 'Error. 404 Not Found.');
										}
										$location.path(REQUIRE_AUTH);
									}
								}
								return $q.reject(response);
							}
							return response;
						}
						return response;
					},
					responseError: function (response) {
						var message;
						currentPath = void 0;
						message = response.headers()['x-status-reason'] || 'Error. Your connection is having a problem';
						$rootScope.$broadcast('error', message);
						if (response.status === 401) {
							currentPath = $location.path();
							if (currentPath !== '/signout' && currentPath !== '/signin' && currentPath !== '/signup') {
								ref = $location.$$url;
								$location.path('/signout').search({
									ref: ref
								});
							}
						}

						return $q.reject(response);
					}
				};
				return exports;
			}
		]);
		return $httpProvider.interceptors.push('ddInterceptor');
```

You look

```                        
message = response.headers()['x-status-reason'] || 'Error. Your connection is having a problem';
$rootScope.$broadcast('error', message);
```

This is example for a error single.
If use array for  multi error, please look

```
								errors = response.data.errors || [];
								if (errors) {
									angular.forEach(errors, function (error) {
										$rootScope.$broadcast('error', error.path + ': ' + error.message);
									});
								}
```
Hope it's useful

**Comment by leduong** [comment]
Hi

This repo https://github.com/leduong/NavigatorGlassWeb 
[![Build Status](https://secure.travis-ci.org/leduong/NavigatorGlassWeb.png?branch=master)](https://travis-ci.org/leduong/NavigatorGlassWeb)

Deploy on heroku
    
    # heroku create
    # git push heroku master

**Comment by stuartshay** [comment]
Can you update this site on your end

http://desolate-basin-6008.herokuapp.com/

 

 

This way I can track changes and add new issues

 

Thanks

Stuart

**Comment by Cristialt** [comment]
OK, I'll look into it tomorrow

**Comment by Cristialt** [comment]
So you want me to get this repo functional with less and deployed to heroku?

**Comment by stuartshay** [comment]
Christi

The deployment is working and I have the other guy making the fixes in the path to CSS that is not getting deployed

I just want to make sure that you can deploy your code to Heriku using your instance this is just a quick test to see that everything is working on your end

Once this is setup on your end we can proceed with new items

Stuart

**Comment by stuartshay** [comment]
Cristian:

 

Any luck with getting the deployment to work on your end.

 

Just send me a link once you have the site working, then we can work on issues.

 

Thanks

Stuart

**Comment by Cristialt** [comment]
I can work on that tomorrow afternoon / morning your time

**Comment by stuartshay** [comment]
Ok, Sounds Good, Once it setup on your end we can go over new requirements

 

Thanks Again

Stuart

**Comment by Cristialt** [comment]
ok great

**Comment by Cristialt** [comment]
@stuartshay 
update: The deployment is working now, I still need to update some of the paths, but I will do that on Saturday afternoon and I'll let you know once I've pushed a complete functional instance, and maybe we'll have a quick chat and see what's next

**Comment by stuartshay** [comment]
Christi:

 

Sounds Great,  I got the code working with the API if you run 

 

> grunt serve:prod 

 

This will call my API and enable you to modify your timetime and display on Glass

 

https://developers.google.com/glass/tools-downloads/playground

Client Key: 126018090035.apps.googleusercontent.com

 

Once you have everything setup and ready to go,  lets have a chat of my direction and what needs to be done.

 

I should be available all day Sunday. 

 

Stuart

**Comment by Cristialt** [comment]
Stuart
When I pushed the latest this week I found everything not working with grunt and the deployment failed again. I see you closed it. The version before pulling this week's commits went fine. I will be off until Monday just wanted to let you know.

**Comment by stuartshay** [comment]
Christi

 

Need to investigate, the deployment is working now

http://agile-ocean-6868.herokuapp.com/#/timeline

 

Just Closed this issue to start fresh, I can reopen it

 

Stuart

**Comment by stuartshay** [comment]
Cristian:

The Code has been deployed, as I stated earlier,  we can get SASS to work but the amount of dependencies and packages it is more overhead then it is worth. 

Going Forward use the current Head (Using LESS)  in the project and see if you can deploy on your end,   

Once you have your deployment working send me the link and we can go over further details.

**Comment by stuartshay** [comment]
Working 
http://navigatorglass.com/
