### ISSUE TITLE
Timeline - Scroll Bar Not Visible on MAC

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorGlassWeb#40]
On the Timeline/Location/Template Tab the Scroll Bar is Visible on Windows on the Mac (FF/Chrome) it is not visible

![scrollbar](https://cloud.githubusercontent.com/assets/887805/5501072/68172c5c-8721-11e4-8451-ccfce2e1ce48.png)

**Comment by Cristialt** [comment]
I wrote a CSS solution to this which covers all the webkit browsers. 
It won't cover FF on Mac though. If you really need a cross browser solution there's a jQuery workaround which I avoided to keep things simple.
