### ISSUE TITLE
Tab Text CSS 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorGlassWeb#46]
The Format of the Tabs should match the Playground Style
See: http://navigatorglass.herokuapp.com/#/timeline

![tab](https://cloud.githubusercontent.com/assets/887805/5987200/51fd232a-a8ed-11e4-9bbc-17c76f6e114c.PNG)

**Comment by stuartshay** [comment]
Issue Not Resolved, Brian will fix

**Comment by stuartshay** [comment]
Something not working 

http://navigatorglass.com/

**Comment by meduccuong** [comment]
I fixed it 2 days ago but It seems missed in this deploy version.

Sincerely,
Cuong, Me Duc

**Comment by stuartshay** [comment]
Yes, I believe you, I think something is with the CSS is not correct.

 

We got the Site working and deployed,  Ask Duong to help with getting the new code the old branch was moved.

 

Thanks

Stuart

**Comment by meduccuong** [comment]
Hi Stuart,
Currently we have two folders for styling: sass and less. Most of them are the same.
We're going to remove sass and use less?
I've updated from less to sass style. Please see it.

![image](https://cloud.githubusercontent.com/assets/6001530/6141920/a42575e4-b1df-11e4-8d44-ff84b532135e.png)
http://glass-meduccuong.herokuapp.com/#/timeline

Thanks,

**Comment by stuartshay** [comment]
Brian

We are not using sass, it won't work for deployment

If we can remove all the sass code would be a good idea

Stuart

**Comment by leduong** [comment]
Brian.

Sass is backup-version, I converted to LESS from SASS. Now, only develop by LESS, if LESS is good, we will remove SASS.


fun
Duong
